services:
  - type: web
    name: dice-roll-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python async_bot.py
    envVars:
      - key: BOT_TOKEN
      - key: PYTHON_VERSION
        value: "3.10"
    healthCheckPath: /health